name: sleap

# - sleap::pyside2=5.14.1
dependencies:
- python=3.7
- sleap::tensorflow=2.7.0
- Pillow
- Shapely
- conda-build=3.17
- anaconda-client
- conda-verify
- pip
- pip:
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"