name: sleap

# - sleap::tensorflow=2.3.1
# - sleap::pyside2=5.14.1

dependencies:
- python=3.7
- cudatoolkit=11.3.1
- cudnn=8.2.1
- Pillow
- Shapely
- pip
- pip:
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"