name: sleap

dependencies:
- python=3.7
- cudatoolkit=11.3.1
- cudnn=8.2.1
- sleap::tensorflow=2.7.0
- sleap::pyside2=5.15.2
- Pillow
- Shapely
- pip
- pip:
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"